name: session_mate
description: Instantly reproduce bugs with a single click, directly from your app.
version: 0.2.0
homepage: https://sessionmate.dev/

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  uuid: ^3.0.7
  freezed_annotation: ^2.4.1
  gesture_x_detector: ^1.1.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  stacked: ^3.4.1
  crypto: ^3.0.3
  vector_math:
  session_mate_core:
    path: ../session_mate_core
  get_it: ^7.6.0
  hive: ^2.2.3
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  build_runner:
  mockito:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
