name: session_mate
description: Instantly reproduce bugs with a single click, directly from your app.
version: 0.4.0
homepage: https://sessionmate.dev/

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

  uuid: ^3.0.7
  freezed_annotation: ^2.4.1
  gesture_x_detector: ^1.1.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  stacked: ^3.4.1
  crypto: ^3.0.3
  vector_math: ^2.1.4
  
  session_mate_core: ^0.1.0

  get_it: ^7.6.0
  hive: ^2.2.3
  path_provider: ^2.1.0
  
  dio: ^5.2.0
  talker_dio_logger: ^1.2.2
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  collection: ^1.16.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  build_runner:
  mockito:
    
  integration_test:
    sdk: flutter

dependency_overrides:
  path: ../session_mate_core


flutter:
  uses-material-design: true
  assets:
    - assets/driver_bar_icons/
    - assets/icons/
    - assets/images/
