name: session_mate
description: Instantly reproduce bugs with a single click, directly from your app.
version: 1.0.0
homepage: https://sessionmate.dev/

environment:
  sdk: ^3.0.6
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.7
  freezed_annotation: ^2.4.1
  gesture_x_detector: ^1.1.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  stacked: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  build_runner:
